const hamburger=document.getElementById('hamburger'),navMenu=document.getElementById('nav-menu'),navLinks=document.querySelectorAll('.nav-link');
hamburger.addEventListener('click',()=>{hamburger.classList.toggle('active');navMenu.classList.toggle('active')});
navLinks.forEach(l=>l.addEventListener('click',()=>{hamburger.classList.remove('active');navMenu.classList.remove('active')}));
const navbar=document.getElementById('navbar');
window.addEventListener('scroll',()=>{navbar.classList.toggle('scrolled',window.pageYOffset>80)});
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',function(e){e.preventDefault();const t=document.querySelector(this.getAttribute('href'));if(t)window.scrollTo({top:t.offsetTop-80,behavior:'smooth'})})});
const sections=document.querySelectorAll('section[id]');
window.addEventListener('scroll',()=>{let c='';sections.forEach(s=>{if(window.pageYOffset>=s.offsetTop-200)c=s.getAttribute('id')});navLinks.forEach(l=>{l.classList.remove('active');if(l.getAttribute('href')==='#'+c)l.classList.add('active')})});
const observer=new IntersectionObserver(e=>{e.forEach(en=>{if(en.isIntersecting)en.target.classList.add('visible')})},{threshold:0.12,rootMargin:'0px 0px -60px 0px'});
document.querySelectorAll('.education-card,.timeline-item,.project-card,.recommendation-card,.contact-item').forEach(el=>{el.classList.add('animate-in');observer.observe(el)});

const radarData={labels:['Languages','AI / ML','Data Eng','Cloud','Analytics'],values:[0.82,0.90,0.85,0.85,0.84],colors:['#C8963E','#2D6A8C','#3A6B1E','#8B5A2B','#6B3A8C']};
function renderRadarChart(){const svg=document.getElementById('radar-chart');if(!svg)return;const cx=150,cy=140,R=100,levels=5,n=radarData.labels.length;svg.innerHTML='';function p2c(a,r){const rad=(a-90)*Math.PI/180;return{x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)}}for(let l=1;l<=levels;l++){const r=(R/levels)*l;const pts=Array.from({length:n},(_,i)=>{const p=p2c((360/n)*i,r);return p.x+','+p.y}).join(' ');const poly=document.createElementNS('http://www.w3.org/2000/svg','polygon');poly.setAttribute('points',pts);poly.setAttribute('fill','none');poly.setAttribute('stroke',l===levels?'#C8963E':'#EDE5D8');poly.setAttribute('stroke-width',l===levels?'1.5':'1');svg.appendChild(poly)}for(let i=0;i<n;i++){const end=p2c((360/n)*i,R);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',cx);line.setAttribute('y1',cy);line.setAttribute('x2',end.x);line.setAttribute('y2',end.y);line.setAttribute('stroke','#EDE5D8');line.setAttribute('stroke-width','1');svg.appendChild(line)}const dp=radarData.values.map((v,i)=>{const p=p2c((360/n)*i,v*R);return p.x+','+p.y}).join(' ');const fill=document.createElementNS('http://www.w3.org/2000/svg','polygon');fill.setAttribute('points',dp);fill.setAttribute('fill','rgba(200,150,62,0.18)');fill.setAttribute('stroke','#C8963E');fill.setAttribute('stroke-width','2');svg.appendChild(fill);radarData.values.forEach((v,i)=>{const p=p2c((360/n)*i,v*R);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.setAttribute('r','5');dot.setAttribute('fill',radarData.colors[i]);dot.setAttribute('stroke','white');dot.setAttribute('stroke-width','2');svg.appendChild(dot)});radarData.labels.forEach((label,i)=>{const p=p2c((360/n)*i,R+22);const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',p.x);text.setAttribute('y',p.y+4);text.setAttribute('text-anchor','middle');text.setAttribute('dominant-baseline','middle');text.setAttribute('fill','#1A2B4A');text.setAttribute('font-size','11');text.setAttribute('font-family','DM Sans,sans-serif');text.setAttribute('font-weight','600');text.textContent=label;svg.appendChild(text)});const ct=document.createElementNS('http://www.w3.org/2000/svg','text');ct.setAttribute('x',cx);ct.setAttribute('y',cy);ct.setAttribute('text-anchor','middle');ct.setAttribute('dominant-baseline','middle');ct.setAttribute('fill','#C8963E');ct.setAttribute('font-size','10');ct.setAttribute('font-family','Cormorant Garamond,serif');ct.setAttribute('font-style','italic');ct.textContent='KJ';svg.appendChild(ct)}
function initSkillTabs(){const tabs=document.querySelectorAll('.skill-tab'),panels=document.querySelectorAll('.skill-bars-panel');tabs.forEach(tab=>{tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');const cat=tab.dataset.category;panels.forEach(p=>p.classList.remove('active'));const panel=document.getElementById('panel-'+cat);if(panel){panel.classList.add('active');animateBars(panel)}})});const ss=document.getElementById('skills');const so=new IntersectionObserver(e=>{if(e[0].isIntersecting){const ap=document.querySelector('.skill-bars-panel.active');if(ap)animateBars(ap);so.disconnect()}},{threshold:0.3});if(ss)so.observe(ss)}
function animateBars(panel){panel.querySelectorAll('.sb-fill').forEach((f,i)=>{const pct=f.dataset.pct||0;f.style.width='0%';setTimeout(()=>{f.style.width=pct+'%'},i*80+50)})}
document.querySelectorAll('.project-card').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,cx=r.width/2,cy=r.height/2;card.style.transform=`perspective(800px) rotateX(${(y-cy)/25}deg) rotateY(${(cx-x)/25}deg) translateY(-8px)`});card.addEventListener('mouseleave',()=>{card.style.transform=''})});
window.addEventListener('scroll',()=>{const s=window.pageYOffset;const h=document.querySelector('.hero-content');if(h&&s<window.innerHeight)h.style.transform=`translateY(${s*0.18}px)`});
window.addEventListener('load',()=>{renderRadarChart();initSkillTabs();document.body.classList.add('loaded')});
